// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pre_process211 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        in_strm_TDATA,
        in_strm_TVALID,
        in_strm_TREADY,
        in_strm_TKEEP,
        in_strm_TSTRB,
        in_strm_TUSER,
        in_strm_TLAST,
        in_strm_TID,
        in_strm_TDEST,
        out_strm_V_V_din,
        out_strm_V_V_full_n,
        out_strm_V_V_write,
        low_threshold,
        high_threshold,
        low_threshold_out_din,
        low_threshold_out_full_n,
        low_threshold_out_write,
        high_threshold_out_din,
        high_threshold_out_full_n,
        high_threshold_out_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state4 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] in_strm_TDATA;
input   in_strm_TVALID;
output   in_strm_TREADY;
input  [0:0] in_strm_TKEEP;
input  [0:0] in_strm_TSTRB;
input  [0:0] in_strm_TUSER;
input  [0:0] in_strm_TLAST;
input  [0:0] in_strm_TID;
input  [0:0] in_strm_TDEST;
output  [7:0] out_strm_V_V_din;
input   out_strm_V_V_full_n;
output   out_strm_V_V_write;
input  [7:0] low_threshold;
input  [7:0] high_threshold;
output  [7:0] low_threshold_out_din;
input   low_threshold_out_full_n;
output   low_threshold_out_write;
output  [7:0] high_threshold_out_din;
input   high_threshold_out_full_n;
output   high_threshold_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg out_strm_V_V_write;
reg low_threshold_out_write;
reg high_threshold_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [7:0] in_strm_V_data_V_0_data_out;
wire    in_strm_V_data_V_0_vld_in;
wire    in_strm_V_data_V_0_vld_out;
wire    in_strm_V_data_V_0_ack_in;
reg    in_strm_V_data_V_0_ack_out;
reg   [7:0] in_strm_V_data_V_0_payload_A;
reg   [7:0] in_strm_V_data_V_0_payload_B;
reg    in_strm_V_data_V_0_sel_rd;
reg    in_strm_V_data_V_0_sel_wr;
wire    in_strm_V_data_V_0_sel;
wire    in_strm_V_data_V_0_load_A;
wire    in_strm_V_data_V_0_load_B;
reg   [1:0] in_strm_V_data_V_0_state;
wire    in_strm_V_data_V_0_state_cmp_full;
wire    in_strm_V_dest_V_0_vld_in;
reg    in_strm_V_dest_V_0_ack_out;
reg   [1:0] in_strm_V_dest_V_0_state;
reg    in_strm_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] exitcond_flatten_fu_164_p2;
reg    out_strm_V_V_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] exitcond_flatten_reg_180;
reg    low_threshold_out_blk_n;
reg    high_threshold_out_blk_n;
reg   [19:0] indvar_flatten_reg_153;
reg    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [19:0] indvar_flatten_next_fu_170_p2;
reg   [7:0] tmp_data_V_reg_189;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_block_pp0_stage0_01001;
wire    ap_CS_fsm_state4;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 in_strm_V_data_V_0_sel_rd = 1'b0;
#0 in_strm_V_data_V_0_sel_wr = 1'b0;
#0 in_strm_V_data_V_0_state = 2'd0;
#0 in_strm_V_dest_V_0_state = 2'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((real_start == 1'b0) | (high_threshold_out_full_n == 1'b0) | (low_threshold_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((~((real_start == 1'b0) | (high_threshold_out_full_n == 1'b0) | (low_threshold_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        in_strm_V_data_V_0_sel_rd <= 1'b0;
    end else begin
        if (((in_strm_V_data_V_0_ack_out == 1'b1) & (in_strm_V_data_V_0_vld_out == 1'b1))) begin
            in_strm_V_data_V_0_sel_rd <= ~in_strm_V_data_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        in_strm_V_data_V_0_sel_wr <= 1'b0;
    end else begin
        if (((in_strm_V_data_V_0_ack_in == 1'b1) & (in_strm_V_data_V_0_vld_in == 1'b1))) begin
            in_strm_V_data_V_0_sel_wr <= ~in_strm_V_data_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        in_strm_V_data_V_0_state <= 2'd0;
    end else begin
        if ((((in_strm_V_data_V_0_state == 2'd2) & (in_strm_V_data_V_0_vld_in == 1'b0)) | ((in_strm_V_data_V_0_state == 2'd3) & (in_strm_V_data_V_0_vld_in == 1'b0) & (in_strm_V_data_V_0_ack_out == 1'b1)))) begin
            in_strm_V_data_V_0_state <= 2'd2;
        end else if ((((in_strm_V_data_V_0_state == 2'd1) & (in_strm_V_data_V_0_ack_out == 1'b0)) | ((in_strm_V_data_V_0_state == 2'd3) & (in_strm_V_data_V_0_ack_out == 1'b0) & (in_strm_V_data_V_0_vld_in == 1'b1)))) begin
            in_strm_V_data_V_0_state <= 2'd1;
        end else if (((~((in_strm_V_data_V_0_vld_in == 1'b0) & (in_strm_V_data_V_0_ack_out == 1'b1)) & ~((in_strm_V_data_V_0_ack_out == 1'b0) & (in_strm_V_data_V_0_vld_in == 1'b1)) & (in_strm_V_data_V_0_state == 2'd3)) | ((in_strm_V_data_V_0_state == 2'd1) & (in_strm_V_data_V_0_ack_out == 1'b1)) | ((in_strm_V_data_V_0_state == 2'd2) & (in_strm_V_data_V_0_vld_in == 1'b1)))) begin
            in_strm_V_data_V_0_state <= 2'd3;
        end else begin
            in_strm_V_data_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        in_strm_V_dest_V_0_state <= 2'd0;
    end else begin
        if ((((in_strm_V_dest_V_0_state == 2'd2) & (in_strm_V_dest_V_0_vld_in == 1'b0)) | ((in_strm_V_dest_V_0_state == 2'd3) & (in_strm_V_dest_V_0_vld_in == 1'b0) & (in_strm_V_dest_V_0_ack_out == 1'b1)))) begin
            in_strm_V_dest_V_0_state <= 2'd2;
        end else if ((((in_strm_V_dest_V_0_state == 2'd1) & (in_strm_V_dest_V_0_ack_out == 1'b0)) | ((in_strm_V_dest_V_0_state == 2'd3) & (in_strm_V_dest_V_0_ack_out == 1'b0) & (in_strm_V_dest_V_0_vld_in == 1'b1)))) begin
            in_strm_V_dest_V_0_state <= 2'd1;
        end else if (((~((in_strm_V_dest_V_0_vld_in == 1'b0) & (in_strm_V_dest_V_0_ack_out == 1'b1)) & ~((in_strm_V_dest_V_0_ack_out == 1'b0) & (in_strm_V_dest_V_0_vld_in == 1'b1)) & (in_strm_V_dest_V_0_state == 2'd3)) | ((in_strm_V_dest_V_0_state == 2'd1) & (in_strm_V_dest_V_0_ack_out == 1'b1)) | ((in_strm_V_dest_V_0_state == 2'd2) & (in_strm_V_dest_V_0_vld_in == 1'b1)))) begin
            in_strm_V_dest_V_0_state <= 2'd3;
        end else begin
            in_strm_V_dest_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_164_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_reg_153 <= indvar_flatten_next_fu_170_p2;
    end else if ((~((real_start == 1'b0) | (high_threshold_out_full_n == 1'b0) | (low_threshold_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_153 <= 20'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exitcond_flatten_reg_180 <= exitcond_flatten_fu_164_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((in_strm_V_data_V_0_load_A == 1'b1)) begin
        in_strm_V_data_V_0_payload_A <= in_strm_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((in_strm_V_data_V_0_load_B == 1'b1)) begin
        in_strm_V_data_V_0_payload_B <= in_strm_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_164_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_data_V_reg_189 <= in_strm_V_data_V_0_data_out;
    end
end

always @ (*) begin
    if ((exitcond_flatten_fu_164_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        high_threshold_out_blk_n = high_threshold_out_full_n;
    end else begin
        high_threshold_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (high_threshold_out_full_n == 1'b0) | (low_threshold_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        high_threshold_out_write = 1'b1;
    end else begin
        high_threshold_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_flatten_fu_164_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_strm_TDATA_blk_n = in_strm_V_data_V_0_state[1'd0];
    end else begin
        in_strm_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_flatten_fu_164_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_strm_V_data_V_0_ack_out = 1'b1;
    end else begin
        in_strm_V_data_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((in_strm_V_data_V_0_sel == 1'b1)) begin
        in_strm_V_data_V_0_data_out = in_strm_V_data_V_0_payload_B;
    end else begin
        in_strm_V_data_V_0_data_out = in_strm_V_data_V_0_payload_A;
    end
end

always @ (*) begin
    if (((exitcond_flatten_fu_164_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_strm_V_dest_V_0_ack_out = 1'b1;
    end else begin
        in_strm_V_dest_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        low_threshold_out_blk_n = low_threshold_out_full_n;
    end else begin
        low_threshold_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (high_threshold_out_full_n == 1'b0) | (low_threshold_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        low_threshold_out_write = 1'b1;
    end else begin
        low_threshold_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_flatten_reg_180 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_strm_V_V_blk_n = out_strm_V_V_full_n;
    end else begin
        out_strm_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_flatten_reg_180 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_strm_V_V_write = 1'b1;
    end else begin
        out_strm_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (high_threshold_out_full_n == 1'b0) | (low_threshold_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((exitcond_flatten_fu_164_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((exitcond_flatten_fu_164_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((exitcond_flatten_reg_180 == 1'd0) & (out_strm_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((exitcond_flatten_fu_164_p2 == 1'd0) & (in_strm_V_data_V_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((exitcond_flatten_reg_180 == 1'd0) & (out_strm_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((exitcond_flatten_fu_164_p2 == 1'd0) & (in_strm_V_data_V_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((exitcond_flatten_reg_180 == 1'd0) & (out_strm_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((exitcond_flatten_fu_164_p2 == 1'd0) & (in_strm_V_data_V_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (high_threshold_out_full_n == 1'b0) | (low_threshold_out_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = ((exitcond_flatten_fu_164_p2 == 1'd0) & (in_strm_V_data_V_0_vld_out == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((exitcond_flatten_reg_180 == 1'd0) & (out_strm_V_V_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign exitcond_flatten_fu_164_p2 = ((indvar_flatten_reg_153 == 20'd921600) ? 1'b1 : 1'b0);

assign high_threshold_out_din = high_threshold;

assign in_strm_TREADY = in_strm_V_dest_V_0_state[1'd1];

assign in_strm_V_data_V_0_ack_in = in_strm_V_data_V_0_state[1'd1];

assign in_strm_V_data_V_0_load_A = (in_strm_V_data_V_0_state_cmp_full & ~in_strm_V_data_V_0_sel_wr);

assign in_strm_V_data_V_0_load_B = (in_strm_V_data_V_0_state_cmp_full & in_strm_V_data_V_0_sel_wr);

assign in_strm_V_data_V_0_sel = in_strm_V_data_V_0_sel_rd;

assign in_strm_V_data_V_0_state_cmp_full = ((in_strm_V_data_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign in_strm_V_data_V_0_vld_in = in_strm_TVALID;

assign in_strm_V_data_V_0_vld_out = in_strm_V_data_V_0_state[1'd0];

assign in_strm_V_dest_V_0_vld_in = in_strm_TVALID;

assign indvar_flatten_next_fu_170_p2 = (indvar_flatten_reg_153 + 20'd1);

assign low_threshold_out_din = low_threshold;

assign out_strm_V_V_din = tmp_data_V_reg_189;

assign start_out = real_start;

endmodule //pre_process211
