// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module xFCannyKernel (
        p_src_mat_V_V_dout,
        p_src_mat_V_V_empty_n,
        p_src_mat_V_V_read,
        p_dst_mat_V_V_din,
        p_dst_mat_V_V_full_n,
        p_dst_mat_V_V_write,
        p_lowthreshold,
        p_highthreshold,
        ap_clk,
        ap_rst,
        p_lowthreshold_ap_vld,
        p_highthreshold_ap_vld,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [7:0] p_src_mat_V_V_dout;
input   p_src_mat_V_V_empty_n;
output   p_src_mat_V_V_read;
output  [1:0] p_dst_mat_V_V_din;
input   p_dst_mat_V_V_full_n;
output   p_dst_mat_V_V_write;
input  [7:0] p_lowthreshold;
input  [7:0] p_highthreshold;
input   ap_clk;
input   ap_rst;
input   p_lowthreshold_ap_vld;
input   p_highthreshold_ap_vld;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    xFAverageGaussianMas_U0_ap_start;
wire    xFAverageGaussianMas_U0_start_full_n;
wire    xFAverageGaussianMas_U0_ap_done;
wire    xFAverageGaussianMas_U0_ap_continue;
wire    xFAverageGaussianMas_U0_ap_idle;
wire    xFAverageGaussianMas_U0_ap_ready;
wire    xFAverageGaussianMas_U0_start_out;
wire    xFAverageGaussianMas_U0_start_write;
wire    xFAverageGaussianMas_U0_p_src_mat_V_V_read;
wire   [7:0] xFAverageGaussianMas_U0_p_out_mat_V_V_din;
wire    xFAverageGaussianMas_U0_p_out_mat_V_V_write;
wire   [7:0] xFAverageGaussianMas_U0_p_lowthreshold_out_din;
wire    xFAverageGaussianMas_U0_p_lowthreshold_out_write;
wire   [7:0] xFAverageGaussianMas_U0_p_highthreshold_out_din;
wire    xFAverageGaussianMas_U0_p_highthreshold_out_write;
wire    xFSobel_U0_ap_start;
wire    xFSobel_U0_ap_done;
wire    xFSobel_U0_ap_continue;
wire    xFSobel_U0_ap_idle;
wire    xFSobel_U0_ap_ready;
wire    xFSobel_U0_start_out;
wire    xFSobel_U0_start_write;
wire    xFSobel_U0_p_src_V_V_read;
wire   [15:0] xFSobel_U0_p_dst_V_V_din;
wire    xFSobel_U0_p_dst_V_V_write;
wire   [15:0] xFSobel_U0_p_dst1_V_V_din;
wire    xFSobel_U0_p_dst1_V_V_write;
wire    xFDuplicate_rows_U0_ap_start;
wire    xFDuplicate_rows_U0_start_full_n;
wire    xFDuplicate_rows_U0_ap_done;
wire    xFDuplicate_rows_U0_ap_continue;
wire    xFDuplicate_rows_U0_ap_idle;
wire    xFDuplicate_rows_U0_ap_ready;
wire    xFDuplicate_rows_U0_start_out;
wire    xFDuplicate_rows_U0_start_write;
wire    xFDuplicate_rows_U0_p_src_mat_V_V_read;
wire    xFDuplicate_rows_U0_p_src_mat1_V_V_read;
wire   [15:0] xFDuplicate_rows_U0_p_dst1_mat_V_V_din;
wire    xFDuplicate_rows_U0_p_dst1_mat_V_V_write;
wire   [15:0] xFDuplicate_rows_U0_p_dst2_mat_V_V_din;
wire    xFDuplicate_rows_U0_p_dst2_mat_V_V_write;
wire   [15:0] xFDuplicate_rows_U0_p_dst1_out_mat_V_V_din;
wire    xFDuplicate_rows_U0_p_dst1_out_mat_V_V_write;
wire   [15:0] xFDuplicate_rows_U0_p_dst2_out_mat_V_V_din;
wire    xFDuplicate_rows_U0_p_dst2_out_mat_V_V_write;
wire    xFMagnitudeKernel_U0_ap_start;
wire    xFMagnitudeKernel_U0_ap_done;
wire    xFMagnitudeKernel_U0_ap_continue;
wire    xFMagnitudeKernel_U0_ap_idle;
wire    xFMagnitudeKernel_U0_ap_ready;
wire    xFMagnitudeKernel_U0_p_src1_V_V_read;
wire    xFMagnitudeKernel_U0_p_src2_V_V_read;
wire   [15:0] xFMagnitudeKernel_U0_p_dst_V_V_din;
wire    xFMagnitudeKernel_U0_p_dst_V_V_write;
wire    xFAngleKernel_U0_ap_start;
wire    xFAngleKernel_U0_ap_done;
wire    xFAngleKernel_U0_ap_continue;
wire    xFAngleKernel_U0_ap_idle;
wire    xFAngleKernel_U0_ap_ready;
wire    xFAngleKernel_U0_p_src1_V_V_read;
wire    xFAngleKernel_U0_p_src2_V_V_read;
wire   [7:0] xFAngleKernel_U0_p_dst_V_V_din;
wire    xFAngleKernel_U0_p_dst_V_V_write;
wire    xFSuppression3x3_U0_ap_start;
wire    xFSuppression3x3_U0_ap_done;
wire    xFSuppression3x3_U0_ap_continue;
wire    xFSuppression3x3_U0_ap_idle;
wire    xFSuppression3x3_U0_ap_ready;
wire    xFSuppression3x3_U0_p_magnitude_mat_V_V_read;
wire    xFSuppression3x3_U0_p_phase_mat_V_V_read;
wire   [1:0] xFSuppression3x3_U0_p_dst_mat_V_V_din;
wire    xFSuppression3x3_U0_p_dst_mat_V_V_write;
wire    xFSuppression3x3_U0_low_threshold_read;
wire    xFSuppression3x3_U0_high_threshold_read;
wire    ap_sync_continue;
wire    gaussian_mat_V_V_full_n;
wire   [7:0] gaussian_mat_V_V_dout;
wire    gaussian_mat_V_V_empty_n;
wire    p_lowthreshold_c_full_n;
wire   [7:0] p_lowthreshold_c_dout;
wire    p_lowthreshold_c_empty_n;
wire    p_highthreshold_c_full_n;
wire   [7:0] p_highthreshold_c_dout;
wire    p_highthreshold_c_empty_n;
wire    gradx_mat_V_V_full_n;
wire   [15:0] gradx_mat_V_V_dout;
wire    gradx_mat_V_V_empty_n;
wire    grady_mat_V_V_full_n;
wire   [15:0] grady_mat_V_V_dout;
wire    grady_mat_V_V_empty_n;
wire    gradx1_mat_V_V_full_n;
wire   [15:0] gradx1_mat_V_V_dout;
wire    gradx1_mat_V_V_empty_n;
wire    gradx2_mat_V_V_full_n;
wire   [15:0] gradx2_mat_V_V_dout;
wire    gradx2_mat_V_V_empty_n;
wire    grady1_mat_V_V_full_n;
wire   [15:0] grady1_mat_V_V_dout;
wire    grady1_mat_V_V_empty_n;
wire    grady2_mat_V_V_full_n;
wire   [15:0] grady2_mat_V_V_dout;
wire    grady2_mat_V_V_empty_n;
wire    magnitude_mat_V_V_full_n;
wire   [15:0] magnitude_mat_V_V_dout;
wire    magnitude_mat_V_V_empty_n;
wire    phase_mat_V_V_full_n;
wire   [7:0] phase_mat_V_V_dout;
wire    phase_mat_V_V_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_xFSobel_U0_din;
wire    start_for_xFSobel_U0_full_n;
wire   [0:0] start_for_xFSobel_U0_dout;
wire    start_for_xFSobel_U0_empty_n;
wire   [0:0] start_for_xFSuppression3x3_U0_din;
wire    start_for_xFSuppression3x3_U0_full_n;
wire   [0:0] start_for_xFSuppression3x3_U0_dout;
wire    start_for_xFSuppression3x3_U0_empty_n;
wire   [0:0] start_for_xFDuplicate_rows_U0_din;
wire    start_for_xFDuplicate_rows_U0_full_n;
wire   [0:0] start_for_xFDuplicate_rows_U0_dout;
wire    start_for_xFDuplicate_rows_U0_empty_n;
wire   [0:0] start_for_xFMagnitudeKernel_U0_din;
wire    start_for_xFMagnitudeKernel_U0_full_n;
wire   [0:0] start_for_xFMagnitudeKernel_U0_dout;
wire    start_for_xFMagnitudeKernel_U0_empty_n;
wire   [0:0] start_for_xFAngleKernel_U0_din;
wire    start_for_xFAngleKernel_U0_full_n;
wire   [0:0] start_for_xFAngleKernel_U0_dout;
wire    start_for_xFAngleKernel_U0_empty_n;
wire    xFMagnitudeKernel_U0_start_full_n;
wire    xFMagnitudeKernel_U0_start_write;
wire    xFAngleKernel_U0_start_full_n;
wire    xFAngleKernel_U0_start_write;
wire    xFSuppression3x3_U0_start_full_n;
wire    xFSuppression3x3_U0_start_write;

xFAverageGaussianMas xFAverageGaussianMas_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFAverageGaussianMas_U0_ap_start),
    .start_full_n(xFAverageGaussianMas_U0_start_full_n),
    .ap_done(xFAverageGaussianMas_U0_ap_done),
    .ap_continue(xFAverageGaussianMas_U0_ap_continue),
    .ap_idle(xFAverageGaussianMas_U0_ap_idle),
    .ap_ready(xFAverageGaussianMas_U0_ap_ready),
    .start_out(xFAverageGaussianMas_U0_start_out),
    .start_write(xFAverageGaussianMas_U0_start_write),
    .p_src_mat_V_V_dout(p_src_mat_V_V_dout),
    .p_src_mat_V_V_empty_n(p_src_mat_V_V_empty_n),
    .p_src_mat_V_V_read(xFAverageGaussianMas_U0_p_src_mat_V_V_read),
    .p_out_mat_V_V_din(xFAverageGaussianMas_U0_p_out_mat_V_V_din),
    .p_out_mat_V_V_full_n(gaussian_mat_V_V_full_n),
    .p_out_mat_V_V_write(xFAverageGaussianMas_U0_p_out_mat_V_V_write),
    .p_lowthreshold(p_lowthreshold),
    .p_highthreshold(p_highthreshold),
    .p_lowthreshold_out_din(xFAverageGaussianMas_U0_p_lowthreshold_out_din),
    .p_lowthreshold_out_full_n(p_lowthreshold_c_full_n),
    .p_lowthreshold_out_write(xFAverageGaussianMas_U0_p_lowthreshold_out_write),
    .p_highthreshold_out_din(xFAverageGaussianMas_U0_p_highthreshold_out_din),
    .p_highthreshold_out_full_n(p_highthreshold_c_full_n),
    .p_highthreshold_out_write(xFAverageGaussianMas_U0_p_highthreshold_out_write)
);

xFSobel xFSobel_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFSobel_U0_ap_start),
    .start_full_n(start_for_xFDuplicate_rows_U0_full_n),
    .ap_done(xFSobel_U0_ap_done),
    .ap_continue(xFSobel_U0_ap_continue),
    .ap_idle(xFSobel_U0_ap_idle),
    .ap_ready(xFSobel_U0_ap_ready),
    .start_out(xFSobel_U0_start_out),
    .start_write(xFSobel_U0_start_write),
    .p_src_V_V_dout(gaussian_mat_V_V_dout),
    .p_src_V_V_empty_n(gaussian_mat_V_V_empty_n),
    .p_src_V_V_read(xFSobel_U0_p_src_V_V_read),
    .p_dst_V_V_din(xFSobel_U0_p_dst_V_V_din),
    .p_dst_V_V_full_n(gradx_mat_V_V_full_n),
    .p_dst_V_V_write(xFSobel_U0_p_dst_V_V_write),
    .p_dst1_V_V_din(xFSobel_U0_p_dst1_V_V_din),
    .p_dst1_V_V_full_n(grady_mat_V_V_full_n),
    .p_dst1_V_V_write(xFSobel_U0_p_dst1_V_V_write)
);

xFDuplicate_rows xFDuplicate_rows_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFDuplicate_rows_U0_ap_start),
    .start_full_n(xFDuplicate_rows_U0_start_full_n),
    .ap_done(xFDuplicate_rows_U0_ap_done),
    .ap_continue(xFDuplicate_rows_U0_ap_continue),
    .ap_idle(xFDuplicate_rows_U0_ap_idle),
    .ap_ready(xFDuplicate_rows_U0_ap_ready),
    .start_out(xFDuplicate_rows_U0_start_out),
    .start_write(xFDuplicate_rows_U0_start_write),
    .p_src_mat_V_V_dout(gradx_mat_V_V_dout),
    .p_src_mat_V_V_empty_n(gradx_mat_V_V_empty_n),
    .p_src_mat_V_V_read(xFDuplicate_rows_U0_p_src_mat_V_V_read),
    .p_src_mat1_V_V_dout(grady_mat_V_V_dout),
    .p_src_mat1_V_V_empty_n(grady_mat_V_V_empty_n),
    .p_src_mat1_V_V_read(xFDuplicate_rows_U0_p_src_mat1_V_V_read),
    .p_dst1_mat_V_V_din(xFDuplicate_rows_U0_p_dst1_mat_V_V_din),
    .p_dst1_mat_V_V_full_n(gradx1_mat_V_V_full_n),
    .p_dst1_mat_V_V_write(xFDuplicate_rows_U0_p_dst1_mat_V_V_write),
    .p_dst2_mat_V_V_din(xFDuplicate_rows_U0_p_dst2_mat_V_V_din),
    .p_dst2_mat_V_V_full_n(gradx2_mat_V_V_full_n),
    .p_dst2_mat_V_V_write(xFDuplicate_rows_U0_p_dst2_mat_V_V_write),
    .p_dst1_out_mat_V_V_din(xFDuplicate_rows_U0_p_dst1_out_mat_V_V_din),
    .p_dst1_out_mat_V_V_full_n(grady1_mat_V_V_full_n),
    .p_dst1_out_mat_V_V_write(xFDuplicate_rows_U0_p_dst1_out_mat_V_V_write),
    .p_dst2_out_mat_V_V_din(xFDuplicate_rows_U0_p_dst2_out_mat_V_V_din),
    .p_dst2_out_mat_V_V_full_n(grady2_mat_V_V_full_n),
    .p_dst2_out_mat_V_V_write(xFDuplicate_rows_U0_p_dst2_out_mat_V_V_write)
);

xFMagnitudeKernel xFMagnitudeKernel_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFMagnitudeKernel_U0_ap_start),
    .ap_done(xFMagnitudeKernel_U0_ap_done),
    .ap_continue(xFMagnitudeKernel_U0_ap_continue),
    .ap_idle(xFMagnitudeKernel_U0_ap_idle),
    .ap_ready(xFMagnitudeKernel_U0_ap_ready),
    .p_src1_V_V_dout(gradx1_mat_V_V_dout),
    .p_src1_V_V_empty_n(gradx1_mat_V_V_empty_n),
    .p_src1_V_V_read(xFMagnitudeKernel_U0_p_src1_V_V_read),
    .p_src2_V_V_dout(grady1_mat_V_V_dout),
    .p_src2_V_V_empty_n(grady1_mat_V_V_empty_n),
    .p_src2_V_V_read(xFMagnitudeKernel_U0_p_src2_V_V_read),
    .p_dst_V_V_din(xFMagnitudeKernel_U0_p_dst_V_V_din),
    .p_dst_V_V_full_n(magnitude_mat_V_V_full_n),
    .p_dst_V_V_write(xFMagnitudeKernel_U0_p_dst_V_V_write)
);

xFAngleKernel xFAngleKernel_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFAngleKernel_U0_ap_start),
    .ap_done(xFAngleKernel_U0_ap_done),
    .ap_continue(xFAngleKernel_U0_ap_continue),
    .ap_idle(xFAngleKernel_U0_ap_idle),
    .ap_ready(xFAngleKernel_U0_ap_ready),
    .p_src1_V_V_dout(gradx2_mat_V_V_dout),
    .p_src1_V_V_empty_n(gradx2_mat_V_V_empty_n),
    .p_src1_V_V_read(xFAngleKernel_U0_p_src1_V_V_read),
    .p_src2_V_V_dout(grady2_mat_V_V_dout),
    .p_src2_V_V_empty_n(grady2_mat_V_V_empty_n),
    .p_src2_V_V_read(xFAngleKernel_U0_p_src2_V_V_read),
    .p_dst_V_V_din(xFAngleKernel_U0_p_dst_V_V_din),
    .p_dst_V_V_full_n(phase_mat_V_V_full_n),
    .p_dst_V_V_write(xFAngleKernel_U0_p_dst_V_V_write)
);

xFSuppression3x3 xFSuppression3x3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFSuppression3x3_U0_ap_start),
    .ap_done(xFSuppression3x3_U0_ap_done),
    .ap_continue(xFSuppression3x3_U0_ap_continue),
    .ap_idle(xFSuppression3x3_U0_ap_idle),
    .ap_ready(xFSuppression3x3_U0_ap_ready),
    .p_magnitude_mat_V_V_dout(magnitude_mat_V_V_dout),
    .p_magnitude_mat_V_V_empty_n(magnitude_mat_V_V_empty_n),
    .p_magnitude_mat_V_V_read(xFSuppression3x3_U0_p_magnitude_mat_V_V_read),
    .p_phase_mat_V_V_dout(phase_mat_V_V_dout),
    .p_phase_mat_V_V_empty_n(phase_mat_V_V_empty_n),
    .p_phase_mat_V_V_read(xFSuppression3x3_U0_p_phase_mat_V_V_read),
    .p_dst_mat_V_V_din(xFSuppression3x3_U0_p_dst_mat_V_V_din),
    .p_dst_mat_V_V_full_n(p_dst_mat_V_V_full_n),
    .p_dst_mat_V_V_write(xFSuppression3x3_U0_p_dst_mat_V_V_write),
    .low_threshold_dout(p_lowthreshold_c_dout),
    .low_threshold_empty_n(p_lowthreshold_c_empty_n),
    .low_threshold_read(xFSuppression3x3_U0_low_threshold_read),
    .high_threshold_dout(p_highthreshold_c_dout),
    .high_threshold_empty_n(p_highthreshold_c_empty_n),
    .high_threshold_read(xFSuppression3x3_U0_high_threshold_read)
);

fifo_w8_d2_A gaussian_mat_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFAverageGaussianMas_U0_p_out_mat_V_V_din),
    .if_full_n(gaussian_mat_V_V_full_n),
    .if_write(xFAverageGaussianMas_U0_p_out_mat_V_V_write),
    .if_dout(gaussian_mat_V_V_dout),
    .if_empty_n(gaussian_mat_V_V_empty_n),
    .if_read(xFSobel_U0_p_src_V_V_read)
);

fifo_w8_d5_A p_lowthreshold_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFAverageGaussianMas_U0_p_lowthreshold_out_din),
    .if_full_n(p_lowthreshold_c_full_n),
    .if_write(xFAverageGaussianMas_U0_p_lowthreshold_out_write),
    .if_dout(p_lowthreshold_c_dout),
    .if_empty_n(p_lowthreshold_c_empty_n),
    .if_read(xFSuppression3x3_U0_low_threshold_read)
);

fifo_w8_d5_A p_highthreshold_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFAverageGaussianMas_U0_p_highthreshold_out_din),
    .if_full_n(p_highthreshold_c_full_n),
    .if_write(xFAverageGaussianMas_U0_p_highthreshold_out_write),
    .if_dout(p_highthreshold_c_dout),
    .if_empty_n(p_highthreshold_c_empty_n),
    .if_read(xFSuppression3x3_U0_high_threshold_read)
);

fifo_w16_d2_A gradx_mat_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFSobel_U0_p_dst_V_V_din),
    .if_full_n(gradx_mat_V_V_full_n),
    .if_write(xFSobel_U0_p_dst_V_V_write),
    .if_dout(gradx_mat_V_V_dout),
    .if_empty_n(gradx_mat_V_V_empty_n),
    .if_read(xFDuplicate_rows_U0_p_src_mat_V_V_read)
);

fifo_w16_d2_A grady_mat_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFSobel_U0_p_dst1_V_V_din),
    .if_full_n(grady_mat_V_V_full_n),
    .if_write(xFSobel_U0_p_dst1_V_V_write),
    .if_dout(grady_mat_V_V_dout),
    .if_empty_n(grady_mat_V_V_empty_n),
    .if_read(xFDuplicate_rows_U0_p_src_mat1_V_V_read)
);

fifo_w16_d2_A gradx1_mat_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_rows_U0_p_dst1_mat_V_V_din),
    .if_full_n(gradx1_mat_V_V_full_n),
    .if_write(xFDuplicate_rows_U0_p_dst1_mat_V_V_write),
    .if_dout(gradx1_mat_V_V_dout),
    .if_empty_n(gradx1_mat_V_V_empty_n),
    .if_read(xFMagnitudeKernel_U0_p_src1_V_V_read)
);

fifo_w16_d2_A gradx2_mat_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_rows_U0_p_dst2_mat_V_V_din),
    .if_full_n(gradx2_mat_V_V_full_n),
    .if_write(xFDuplicate_rows_U0_p_dst2_mat_V_V_write),
    .if_dout(gradx2_mat_V_V_dout),
    .if_empty_n(gradx2_mat_V_V_empty_n),
    .if_read(xFAngleKernel_U0_p_src1_V_V_read)
);

fifo_w16_d2_A grady1_mat_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_rows_U0_p_dst1_out_mat_V_V_din),
    .if_full_n(grady1_mat_V_V_full_n),
    .if_write(xFDuplicate_rows_U0_p_dst1_out_mat_V_V_write),
    .if_dout(grady1_mat_V_V_dout),
    .if_empty_n(grady1_mat_V_V_empty_n),
    .if_read(xFMagnitudeKernel_U0_p_src2_V_V_read)
);

fifo_w16_d2_A grady2_mat_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_rows_U0_p_dst2_out_mat_V_V_din),
    .if_full_n(grady2_mat_V_V_full_n),
    .if_write(xFDuplicate_rows_U0_p_dst2_out_mat_V_V_write),
    .if_dout(grady2_mat_V_V_dout),
    .if_empty_n(grady2_mat_V_V_empty_n),
    .if_read(xFAngleKernel_U0_p_src2_V_V_read)
);

fifo_w16_d3840_A magnitude_mat_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFMagnitudeKernel_U0_p_dst_V_V_din),
    .if_full_n(magnitude_mat_V_V_full_n),
    .if_write(xFMagnitudeKernel_U0_p_dst_V_V_write),
    .if_dout(magnitude_mat_V_V_dout),
    .if_empty_n(magnitude_mat_V_V_empty_n),
    .if_read(xFSuppression3x3_U0_p_magnitude_mat_V_V_read)
);

fifo_w8_d2_A phase_mat_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFAngleKernel_U0_p_dst_V_V_din),
    .if_full_n(phase_mat_V_V_full_n),
    .if_write(xFAngleKernel_U0_p_dst_V_V_write),
    .if_dout(phase_mat_V_V_dout),
    .if_empty_n(phase_mat_V_V_empty_n),
    .if_read(xFSuppression3x3_U0_p_phase_mat_V_V_read)
);

start_for_xFSobelncg start_for_xFSobelncg_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFSobel_U0_din),
    .if_full_n(start_for_xFSobel_U0_full_n),
    .if_write(xFAverageGaussianMas_U0_start_write),
    .if_dout(start_for_xFSobel_U0_dout),
    .if_empty_n(start_for_xFSobel_U0_empty_n),
    .if_read(xFSobel_U0_ap_ready)
);

start_for_xFSupprocq start_for_xFSupprocq_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFSuppression3x3_U0_din),
    .if_full_n(start_for_xFSuppression3x3_U0_full_n),
    .if_write(xFAverageGaussianMas_U0_start_write),
    .if_dout(start_for_xFSuppression3x3_U0_dout),
    .if_empty_n(start_for_xFSuppression3x3_U0_empty_n),
    .if_read(xFSuppression3x3_U0_ap_ready)
);

start_for_xFDuplipcA start_for_xFDuplipcA_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFDuplicate_rows_U0_din),
    .if_full_n(start_for_xFDuplicate_rows_U0_full_n),
    .if_write(xFSobel_U0_start_write),
    .if_dout(start_for_xFDuplicate_rows_U0_dout),
    .if_empty_n(start_for_xFDuplicate_rows_U0_empty_n),
    .if_read(xFDuplicate_rows_U0_ap_ready)
);

start_for_xFMagniqcK start_for_xFMagniqcK_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFMagnitudeKernel_U0_din),
    .if_full_n(start_for_xFMagnitudeKernel_U0_full_n),
    .if_write(xFDuplicate_rows_U0_start_write),
    .if_dout(start_for_xFMagnitudeKernel_U0_dout),
    .if_empty_n(start_for_xFMagnitudeKernel_U0_empty_n),
    .if_read(xFMagnitudeKernel_U0_ap_ready)
);

start_for_xFAnglercU start_for_xFAnglercU_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFAngleKernel_U0_din),
    .if_full_n(start_for_xFAngleKernel_U0_full_n),
    .if_write(xFDuplicate_rows_U0_start_write),
    .if_dout(start_for_xFAngleKernel_U0_dout),
    .if_empty_n(start_for_xFAngleKernel_U0_empty_n),
    .if_read(xFAngleKernel_U0_ap_ready)
);

assign ap_done = xFSuppression3x3_U0_ap_done;

assign ap_idle = (xFSuppression3x3_U0_ap_idle & xFSobel_U0_ap_idle & xFMagnitudeKernel_U0_ap_idle & xFDuplicate_rows_U0_ap_idle & xFAverageGaussianMas_U0_ap_idle & xFAngleKernel_U0_ap_idle);

assign ap_ready = xFAverageGaussianMas_U0_ap_ready;

assign ap_sync_continue = ap_continue;

assign ap_sync_done = xFSuppression3x3_U0_ap_done;

assign ap_sync_ready = xFAverageGaussianMas_U0_ap_ready;

assign p_dst_mat_V_V_din = xFSuppression3x3_U0_p_dst_mat_V_V_din;

assign p_dst_mat_V_V_write = xFSuppression3x3_U0_p_dst_mat_V_V_write;

assign p_src_mat_V_V_read = xFAverageGaussianMas_U0_p_src_mat_V_V_read;

assign start_for_xFAngleKernel_U0_din = 1'b1;

assign start_for_xFDuplicate_rows_U0_din = 1'b1;

assign start_for_xFMagnitudeKernel_U0_din = 1'b1;

assign start_for_xFSobel_U0_din = 1'b1;

assign start_for_xFSuppression3x3_U0_din = 1'b1;

assign xFAngleKernel_U0_ap_continue = 1'b1;

assign xFAngleKernel_U0_ap_start = start_for_xFAngleKernel_U0_empty_n;

assign xFAngleKernel_U0_start_full_n = 1'b1;

assign xFAngleKernel_U0_start_write = 1'b0;

assign xFAverageGaussianMas_U0_ap_continue = 1'b1;

assign xFAverageGaussianMas_U0_ap_start = ap_start;

assign xFAverageGaussianMas_U0_start_full_n = (start_for_xFSuppression3x3_U0_full_n & start_for_xFSobel_U0_full_n);

assign xFDuplicate_rows_U0_ap_continue = 1'b1;

assign xFDuplicate_rows_U0_ap_start = start_for_xFDuplicate_rows_U0_empty_n;

assign xFDuplicate_rows_U0_start_full_n = (start_for_xFMagnitudeKernel_U0_full_n & start_for_xFAngleKernel_U0_full_n);

assign xFMagnitudeKernel_U0_ap_continue = 1'b1;

assign xFMagnitudeKernel_U0_ap_start = start_for_xFMagnitudeKernel_U0_empty_n;

assign xFMagnitudeKernel_U0_start_full_n = 1'b1;

assign xFMagnitudeKernel_U0_start_write = 1'b0;

assign xFSobel_U0_ap_continue = 1'b1;

assign xFSobel_U0_ap_start = start_for_xFSobel_U0_empty_n;

assign xFSuppression3x3_U0_ap_continue = ap_continue;

assign xFSuppression3x3_U0_ap_start = start_for_xFSuppression3x3_U0_empty_n;

assign xFSuppression3x3_U0_start_full_n = 1'b1;

assign xFSuppression3x3_U0_start_write = 1'b0;

endmodule //xFCannyKernel
